In [4]:
import numpy as np

In [8]:
array = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
print(array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [6]:
zeros_array = np.zeros(3)
print(zeros_array)
ones_array = np.ones((2, 3), dtype=int)
print(ones_array)
range_array = np.arange(10)
print(range_array)

[0. 0. 0.]
[[1 1 1]
 [1 1 1]]
[0 1 2 3 4 5 6 7 8 9]


In [7]:

print(ones_array.shape)
print(ones_array.dtype)

(2, 3)
int32


In [9]:
print(array[0, 1])
print(array[0, :])
print(array[:, 0])

20
[10 20 30 40 50]
[10 60]


In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


In [11]:
print(np.mean(range_array))


4.5
